/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\jsonHunterTheme.ts
 * Command: astryx theme build src\theme\jsonHunterTheme.ts --out src\theme\jsonHunterTheme.css
 * Generated: 2026-07-29T17:51:45.721Z
 */

/**
 * json-hunter theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { jsonHunterTheme } from './json-hunter';
 *   import './json-hunter.css';
 */
export const jsonHunterTheme = {
  name: 'json-hunter',
  __built: true,
  tokens: {
    "--color-data-orange-4": "light-dark(#D66100, #D66100)"
  },

};
