/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\theme\jsonHunterTheme.ts
 * Command: astryx theme build src\theme\jsonHunterTheme.ts --out src\theme\jsonHunterTheme.css
 * Generated: 2026-07-29T17:51:45.721Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const jsonHunterTheme: DefinedTheme;
